apiVersion: ENC[AES256_GCM,data:X5s=,iv:V4v0XpTGJFT/duNgeBTIeX4oIUj5Z8QdVqfU/2JyoSk=,tag:wBTEsNR7OIf8r3ct7qu9JA==,type:str]
kind: ENC[AES256_GCM,data:foTQG2LJ,iv:ZYNKvsiT209Pb5rAEsMWAVTPlmrUG7kmgGpjD3MN+1s=,tag:pZAXsOyKJpg6PbqYOQikhQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bX1JoQE2QtA2s1pJEmWs,iv:eIE3BGj3/w+8hr+/jOWXNNmh1vqLx7ne+0RMxfBys7k=,tag:5wSvcsWCklEStzdYmLnQXw==,type:str]
    namespace: ENC[AES256_GCM,data:KzoRxBDQ/A==,iv:S7wYTTabGw47Nns6bddwbd/jHDsno4iDTs4AFs0Ni7I=,tag:iAtyONL6Daztw+DACjoaow==,type:str]
type: ENC[AES256_GCM,data:KSViLEbp,iv:BbW/o0EjGIXRgg3mqnVA/ZfLRn/l/uiQFhxzw0XZXDQ=,tag:n+HFrKpvlTXlozu6bjUvQw==,type:str]
stringData:
    keys.yaml: ENC[AES256_GCM,data:Vg1m1aPAGO8Qix0xS0CIgiz7OYaegaeaAjMY5CKCNbGshDybEWI+jOYiJ7gw4/o5VaSZrrprZC6mFxpRBUrt7XklVcBN5lksQOk=,iv:SYbTn7f1sycNHuqRA13Dl9qaUOOqKj1vg6J1ZCOG9mw=,tag:I73avEdq0qktIj5SfLmqGQ==,type:str]
    LIVEKIT_KEY: ENC[AES256_GCM,data:3BQ2QQl1rw==,iv:uX470lJNSEhiMaeXbTkfFAjTJ255Um/LmsKqLG8EuCs=,tag:mJQGpIAULjreZLtUMuICWw==,type:str]
    LIVEKIT_SECRET: ENC[AES256_GCM,data:3kGSWgTjAHRqTxRuYpUNwUByQMII/B2wSydzdQ//p1Lysr+UkArozHMxjl8bkCKIJqKutAYyAZ2T76PRaXc2Dw==,iv:KwUrLV7q/8Q5jNzYPYWQwkUbWg4lP2sY4APLW85hnpI=,tag:CUmbpuzfNpIrYCluxF99Jw==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZXo5eTBuNjFGMmJLd1Rm
            UWFWVEQzZW5IbUVuWlJaOFJMK2lVSW02SERNCm1DdGIrOUIzcS9PUEtQbkZPcWhX
            QUhtZDNlZXdkKzdhMFpwZ1RPcGJieW8KLS0tIC9iMkJmNWlvS3lTVFloTXovZU9i
            bWFxSHhSQkdMSkRnTk9DWk5hZEpCK0UKmu/QawX/d5OeehiL18SI1V9D8+UnUp+j
            TGj8tgEQfSJ2+6ef3+0hSx2lnsI2TIxN7et+LCGzs9x03eJ+G1dkag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T23:17:30Z"
    mac: ENC[AES256_GCM,data:2gQ0vDUtgs+J6r2y+evOO3twr0y9/awX+u8WLSfMgMONItcZdkBkfCKZiivFesRT1JZwkTO9cEG28J+n2iGVnhZJYBMVabwTucNwLiJnaRLHRJ/xDmEHIg8NGa1l/GRNOq0GaPE9joQF4IFq0VGFGmvyzxwtjk4BXg6h7dgRbec=,iv:x+ElyvA3TxVGpJSNXExPr/U4ebYcoP6tdNDRLiqboIQ=,tag:gfiktDzT7b4WT8DGynwRvQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
