apiVersion: ENC[AES256_GCM,data:ygQ=,iv:wvB1evcs7LAtzQ4z6VIMgB2jZAvF7Wz5VMnecFEe1cA=,tag:6y5Aai4CV2lh4ScSOSrfJg==,type:str]
kind: ENC[AES256_GCM,data:cuG+peUV,iv:IQpbFrXwy+gCNmmLxBIqpB5JsLxRofQ0qsmS7+VuLU0=,tag:gpCKTHuXgB0aYam7quiq/w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8xOEn9r0sRk0ZENDSIK2JQ==,iv:/ijW+77TcX1bqXDWttUZAiti2ytvox2bNW8xW68gdLA=,tag:VXcDUU1MAl/bK+aksZQQ7w==,type:str]
    namespace: ENC[AES256_GCM,data:wRFyIISj+Cc=,iv:318lXudU+pgb2XnFhzBTbe+m3getGG+g6/+6wWbuEgE=,tag:g5E7jd8IGrSx+J2xPoJZJw==,type:str]
type: ENC[AES256_GCM,data:bikj4kIQ,iv:HFZDh9Yrtj0W7ljUrXv3QIbjVLZjfSSqHDGjMOAB4x0=,tag:tDqLw1dkZWjAr9IZ1juHYg==,type:str]
stringData:
    RESTIC_PASSWORD: ENC[AES256_GCM,data:DvIIjcjBnW3cWsD+WPUFP/ivbu9or9KyJSD5b4Al+doWpJKhgWNBPo8wqck=,iv:CtLrI2pOJLPyNlkrCIbvZwTbiYC+bKb3/rkE1Dgfc/4=,tag:fKXyGo8PIZCFs7GqNJxTdQ==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:oxfqsmyo0ok=,iv:2LmIxwRA6MiIG1pjF4cWLo1qkbvNtXnQVGtBDalXwIM=,tag:ArYJvDiBzoW44D7er2vcpQ==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:qaAWDczKZ5DPuErZW3cB3nIkdwhhr7xSLjbNeBZRPCG5QNqXFPv/0TT9i47Qdl+yUM/MJjdDDTW37cdfL7X/Rg==,iv:VqCq0fBg7cZpW5HtlDG6jUwaG86mSKVp2oouWeN4V98=,tag:S871yzhxaZIld5+vE9/5Lg==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJNWQ4NEp1bWFLczh3bm9q
            aFdLSk1LU3lQTkp4MVdpYldlN08wdndqRXhvCmo3c3l2SUVLZFNHcHpjMlZCamxK
            SGtDQ1lQRVhsV2N3V1ZBTWhrZWp4MTQKLS0tIDA3VXRjdkxsSTdNZ3grWTZNN3pi
            VFhPa2hXMEtiZWsxaE5UY1hVNithZUkK66Te/BLK+a/5E8pYjM5DvrGUd33pXkev
            EDd1ql+fC12XUVwz2xQTsDh5Y8TMGEC+6c/rUgoweASKzoTBD9ta6g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T09:38:50Z"
    mac: ENC[AES256_GCM,data:XOnQy2JdOwU8f5nCFmm6qJpeGnnQsrJU3FktIhZ6qKT11eZ7g1Rzy63hnlnOFBo4T/Jay9eGGElXLhZlb2vA4Q75N6ls5WN0IVenWXM6MjsLbiHIqvmApSgaVAgYwgtGizBF1n6P6y2hObSY385RkWdzPpCFsGWYXLiWFKiqUP4=,iv:3pT0ON0dclk+TBzFUCYZcdfEBNC2XXKD9osV3yxwgtI=,tag:nFGA0HRjPmScaOOfo6lvww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
