apiVersion: ENC[AES256_GCM,data:us4=,iv:U7i9X5r4oPV9EdlNGBlyoAiiYtcp45ttXjHk7+m3KZI=,tag:of4ubqYAMNJjp/ONPgqu+g==,type:str]
kind: ENC[AES256_GCM,data:dyk1LeyJ,iv:CINtYkl0pE45CcHMa1Jh50P5CUyMFaKsSFFd5+FlY2s=,tag:ZJoArI4HqplzN4/o5Td7YQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CK6638d9/I1iFGjanA==,iv:vsxfcQPqdyQ+lWzj3qzX12T60w6p9g8w8V/50jFFLUE=,tag:TRGgbymZCwo3VMRQldf6YA==,type:str]
    namespace: ENC[AES256_GCM,data:3kO/jos=,iv:71omFKW36HsvBa/xxqdimDfW1nXBpqcjJZRTQEXB1K8=,tag:Le82UHd0HfpWY2pHMvqOCA==,type:str]
type: ENC[AES256_GCM,data:m8VuQLWL,iv:S2l6hAIBB/xzY9pqpCv2RhSVTU3yNVEerv7v2QFvTPc=,tag:vThSctNu4uZDSf8CAbPzSA==,type:str]
stringData:
    secret-key: ENC[AES256_GCM,data:6KoObvMZcwsmMZ2KAF+XW6xELjG59Qbnta8J9uKZCfh6p/1uSLMxC17iCSPTaQKuklVgAjPOgHeNlRWQLBSsJA==,iv:mjjsbDCivEghHeaucKi+yoJNuXFvb8e9fbTEYLCtynQ=,tag:2SC+gqakxtgU7D9YSz/Kgw==,type:str]
    initial-account-password: ENC[AES256_GCM,data:QCjx0N0PQTEiqXhjs2dEU/qLj75B/8oztMuB9HiUZwk=,iv:zkSjqGVxlYSpog59I9uzHu/WRX8b5Rq39MXALfGRfcA=,tag:mjAwhOZj9FZpyuxnVur7IA==,type:str]
    roundcube-db-password: ENC[AES256_GCM,data:u4MZTQ/gGHJApGj61xspvCASPq+jc8tTgrcjZCCb2Ic=,iv:2HxbLl75ZsM1EN1rBbVlTpnSUmX98gBofH/2ugyqw0A=,tag:5J2DBQM4+iP6hmjallufOg==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVlhOalJrU01YbjcweWlF
            cEZoQUFxRUtGMU1xY1BJODZpYlYxcWF0TWtjCnRtbytWdmI3Wk5Hdk9XTnlGZnB4
            TlMxOXlaTGhtK2NqYlNQZU9QNnV2a0kKLS0tIDVRcVZwS2I5LzRJaXJOZ1Zvc1hB
            MHNMWXk1UzRYdWcyVTltRnlmOU5TcmMKw+T5HiJ2yGYZrWIFsMimRNR2uC/CMapi
            mM2cnECAGjdIypcHIZfxl/CejgxPPom57MMHvy/vPW6QkQQ+Osyotw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-23T14:29:50Z"
    mac: ENC[AES256_GCM,data:1xBbaH4qk2DMDk1mzruTHCd0Nps7+koHTMqcgkXX9qQt8tIei0neO9ZSJNKL9rOZUmz2HVB0qGono82DsfKKZJyQ/qQIZbdHh6iRXHBPysqKrBu8aOvlXZ8wixD9VrzkH5EeK9cYtbz3024tv0KrhleXdjhItrGKCNo5kgIkqaw=,iv:boKgpK4YNXYL5U83sAwyHkFhsLKhBHyyZBNgircNIYs=,tag:9YFD9uNlIFbR9CqnDYOaPQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
