#ENC[AES256_GCM,data:/UnyFYRA3cn6C7A8+WYxYamdQXwJozhCngMFnSsnduhSkb5gVj7A5slLt552UOP3aDuPnXHBE99lPXMUlX+GGUiEEx/bwFLh97VOcGe5kw==,iv:pQ3Hr9WRRQxG0zuGekhjiM5M7lVBYvnU714U1T5Utq8=,tag:QglnkO9FS0o2DxrX5T8JLg==,type:comment]
#ENC[AES256_GCM,data:Uoo6PslhvPPiBuxPWYt9r1BkNvJtsGxP3U4yvb7A1R5E9o1jqh+LKOTSC3qRf7mceELwbTVT/4fGxd14350lb1Wv/NnFsKprNPwTaBY=,iv:YwvbQjrlJGBRCnKVsTF+Arg7/NsU/fnKy/UNTSvun1U=,tag:w7gQxeg0Ue3dTaJDA1n2PA==,type:comment]
#ENC[AES256_GCM,data:Ch0ufXwvB+gxf5mMrwbtNHLbxOepcO3dxLTxjd90udXOpRG8sSQtZzYGxAlk/DlPHYY5IASxwx+Ky9nmKFAVeoghQtA2eSc=,iv:pjAuPXE10yv735HuNuPLDI4JpCHCsveMi/FAe9m1pSo=,tag:63P2Lr7rmm3GQ3QFZuhpnw==,type:comment]
#ENC[AES256_GCM,data:cUyWtwM66FigwUcU4g9R7kPoS16W/yDcFBcILPuwWqRLQ3Ekp0cdmiPW5YTh+3jdkaYxJsgICGVxlWq6LuKeNuzK3cqPVOoYrg==,iv:D0DXjSldzmfRogzKZb6eNFaSEC5Jqt1iEi1NNcUY9lg=,tag:Q69FaKJcU9lk8q10RYUk6g==,type:comment]
#ENC[AES256_GCM,data:Ptbluj/xh1NmQlDMWwsy/Lcn4DcvbDypInq39JNIgOOOQRq0sK9eCIG7KGzHMFfYg0HgAJNFsun8UQh8a6eOtg==,iv:EXYcsYsaGrkwggGdJ9ciqen2sJz8ZHOOjGsay/iqtRU=,tag:uklF4kwHB4SBgiroVODkfw==,type:comment]
ARGOCD_ADMIN_USER: ENC[AES256_GCM,data:o3qaFuc=,iv:Fq7Uetmp/eKXFOTnh7PVA07evaJt4zR5cstE6jDcSco=,tag:6UDPm5O8PqZZTNdZwB53JQ==,type:str]
ARGOCD_ADMIN_PASSWORD: ENC[AES256_GCM,data:z7DerXTD1+z/FuFB5n8WQCX/VZD+aoPA,iv:sa7btCdJaI3nEVDIfM9nICD+/ZBeCWwvZ48tWZkOjIE=,tag:30TbflAmPblmVT5kt/6AXQ==,type:str]
ARGOCD_ADMIN_PASSWORD_BCRYPT: ENC[AES256_GCM,data:ySRIym3guVnfkYNr+ujgeNOrHW3RVLhWSH+an2sf3mc4aLoRaun2Pab7WeD79fr/X2dYLwqTziVW6hZQ,iv:79qKNzIgbGeZA2uDqu/fjO6OMvy84+BAGBsXY0wesdA=,tag:yK2ksnuKPsUw9vpSzX8wdg==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDYVA2Z2I3Q1BhMEpHelJT
            SzJiTkdQZGZWUmhoVHIyVVphSzRvUUlzQldJCkxLTHVDMVQ2YmdodWY5dDFtY3Ns
            cTV4NzBYSGI2RmtVTi9xZXRWNFMrYk0KLS0tIDN5N3lIbUxBSWptQkRGYXVvZ0tU
            V3RIajJNY05NY0VJN1pLa2VDK2pUSmcKHgmN4T6gIiUfFI9gKtMYLMO14bwp4MS4
            wSi8LbH/vQ0ie7YaPm4ffRaBzdRAA8ZaroRNeFXJkgve9UvT7wXWSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T18:35:29Z"
    mac: ENC[AES256_GCM,data:Su9Au1YfO21lrs/IeZkCYnG9PzaaHI0xN/btiIcQmGJ3gTiew84Rp2wTDQGbTatyqK5cEi1d0oHn7rL7XWpkFGrFQC7skYs5QRrupQAMUdbhSV86Hgr53/qRhjj0E1TrZ57FHXMl3I5DRhvUlTXLwQhflYaZdGysyGPU6B8SyVA=,iv:Di1CaqXpsX12ONAFINOGFYe8+rKnCTkgfjdAK2o53Tc=,tag:cNEu439sNtm8J1+PQaMC3g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
