apiVersion: ENC[AES256_GCM,data:/fw=,iv:o3/0dIwty0cmZOFxyQl8wlHU4UcmX3ymdWa7Xolnev4=,tag:RC++U2qTlwxvlgicRSDDBQ==,type:str]
kind: ENC[AES256_GCM,data:CMJPIz8p,iv:+nJvRTqmTnOXmi9BVVPj+77Ef1qpXMn123fRlaHA06g=,tag:DZY/h7B7E/3Sq4exHn638Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:2AscElNgNP39rA6iejIYY8DJzw==,iv:va4NjyLca+RYLXcB+taDEhcukdxMKEEDQXU2Ozx4xQg=,tag:75EDwOkpPz2wB8bkCITJUw==,type:str]
    namespace: ENC[AES256_GCM,data:U8ShjLqBoTt7vg8=,iv:rc8gtVFhM3//xS/+5aAodduGBxCJfdhGrT01yyD5YKI=,tag:hgMdSp48Psq4lAmKurdBqA==,type:str]
type: ENC[AES256_GCM,data:+aPPl86r,iv:FuVp78Hob7Yqstz7KxGzpcNGcevieyM8M/nadhTEqDA=,tag:v0cn8qftu0jyVpU0MhGeFg==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:Kqc1vSNqQoBR+B1rtvJHF77MS8hxW4ktaT/2uI7O57Mxl517rpnYLvNpxNj0km2vJ6SjoxAYh3E6UrElTXtBJQ==,iv:XOpBuRi0brJWXdiSnkz38oh2WQHdI9FMb1X0P+Uk1Nk=,tag:qyumbNAb9xaJ4nStJdO+Yw==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SUZWeFdIRTlocVkrc3VE
            bFlnSnB0NVp4dkhYMFdDUmNXZFl0Z0hoaGo0Cjl1b3JLMTk3NTlUNHcwbFdJSFFV
            dmtnaTMvaTVwK2k2c1ZwUVdMVG5lbW8KLS0tIFo4aXdIdDYxYkNqNmF6TzVNSWw1
            RXhTOXZuUk1qRngwelh2QXFHMWdXOEUK4IbypXuEMFQip4LUJ8BmFk6CF6PKgDZT
            doC47IBjak0Cp5kJF0FSirS4VWwPf+/wAxgLwBmVBff8+RjRQ3kkdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-07T22:33:04Z"
    mac: ENC[AES256_GCM,data:eAUrWTVYgYoQXpji2fnpCY1yiGTaY6aLZUQLahGOOh/xGe7twi6J2347nSebXjOy0HqOPcSUzAKHr2KijtV7NRFDh+rNggNMTsigGDAbcQEkJhk+3LQTiQFuh0Qa80cDkS7Yg6hdCz0cNg1KlPxTzgmkIdXJUc49sO3ZHP3F0/E=,iv:iB/DLRQdKKOFsehoRaqHQm06Ucgw4C8P3b7djvzXZXU=,tag:4zhDxpqPE1Xd9TEgVSQkWg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
