apiVersion: ENC[AES256_GCM,data:hIk=,iv:s2gAytF49XLQ7cX4VB03jNzJLWXbEcPQl3OeTcvJ4ug=,tag:UhmUchwquBTZynJlsYmccQ==,type:str]
kind: ENC[AES256_GCM,data:T7qjyYOH,iv:8hD/s8v+Ikmuy03tmaprK306Yrnj+y2Oz+8TBS9Q7hs=,tag:plAmNWSCvGJFOC2D6k+lqg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DHqMoQwfIbTaH+HAJbN0N8u4qA==,iv:RnNbDWAQpBs+cruDI3j+aJEolkWjrN12+JVm0citxzA=,tag:9zSVgu9iNxlqSkuzC3UTeQ==,type:str]
    namespace: ENC[AES256_GCM,data:Jd+7HWnuOIa4P3k=,iv:bG+gNOdXwK8mPNTHBWs+PI/MauXxKLoSwaS3A1BXVq4=,tag:S8iscinhEpAYvI4yEvzaAA==,type:str]
type: ENC[AES256_GCM,data:UQWcKg/n,iv:gbFYAiprzRMh9qEnxLcdN5qPAKbzunkV9Qigw+d23lI=,tag:mlTS/pVPcVmUJgVHAhXlyw==,type:str]
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:aeTSeA2XfI/XjZKPhUNVr6vmwNrQlY2r+itcg+qaOeHfomuICsdqxjfsVUDVRIMYvwN/3npyJwybhjY/jhvFWw==,iv:WExM8LpCrjg+9j21acQ+4acb8foHIQ1rAsroikwQmcg=,tag:dYtc4tEONC+3PshdjvaYZg==,type:str]
    SSO_CLIENT_ID: ENC[AES256_GCM,data:DLjF6z2JHrfmYZ0=,iv:d8QbK/UJUz+P6NkesJmsowSdW1Bcan5VXsLJtipmicA=,tag:XKUAaRySP6WCye28bO8iXg==,type:str]
    SSO_CLIENT_SECRET: ENC[AES256_GCM,data:pmeFLjxrrDXmkr5wh25SjqmIIg+Yug3ZzlmlbqaXcP/xP5QVcrZRdf/QOIpoCMDtm4Oc1AxpdLLOcJ8M7ZhaHw==,iv:6/SwW/mAwKkHFlwx1AcPZmQOtK+VWwsnxZx3mGPLxTE=,tag:id3xI45Ur7KESVc/Q4uxsQ==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNjkrR3huWlZ4SmFEaVQy
            VDhaSkRkTTNoRjhaN0c1N2lFTGl2bmhZdFU0ClRBeDlkQzg0Ym14ZDVxMzdZK0lM
            TmpkbDlGR0wyLzNhUVZ3SjlRQzdUTkkKLS0tIEZLa1JpZldpUGhXVEYzeW9PWjNQ
            ZU03aFlmTXlZKzdzZXAxOEZlSnhyWkUKQynsDKvU5hxSDFJkdxzIkRr+Nf0E2pYo
            ojrrKKr/t/sXUGaEnIyZf387K0DS4BYKfp757c40eD8uM1OKxjXUPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-08T00:08:02Z"
    mac: ENC[AES256_GCM,data:M/KsWk3OJRTPk6Jf1zTMydyo8hnSgC9qtPlfcBH+/PvI3g5e1Qc5VVk+d1iYZ8CunOUxTdFJZr2WOdevMk6Bt5GX3gpLQhmcsxY9/mRKmv5gtlVZAX09C6stKy5d/HhQUxopeRtEsCMx7TzyYH2+vqkir1aIJm6gd71+O6KJf3o=,iv:luZhPXbH+MYP+e9IqxzRrDJSkpqCtiHJk8rL6mec7VM=,tag:zY0avFWkGfLLZPLB7d7aCw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
