apiVersion: ENC[AES256_GCM,data:0/Y=,iv:gy2elGGx9gyhJiezuFrC7RGqw8FGdQ/vGnkvcDqtveY=,tag:l0IA9Kc+URVQcTSDjFBbAA==,type:str]
kind: ENC[AES256_GCM,data:RamIegNI,iv:6JFyFig6kTzky0jwAfDTQt8+CR2URallhqk0ehUnNnU=,tag:1v5j+/YnwYBakenbQMpcnQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:mkhtdxRKIODHMmGnlZN1,iv:7OP0P+5Om0jQ8QdQHkpNswI90vjoTcV6kH7JkA3sdwE=,tag:eepwhKg384OgMzb8HDapig==,type:str]
    namespace: ENC[AES256_GCM,data:S/gY0uQt8w==,iv:uhaU9qeitfbQI7FGcXI4h16eCTgLRVkO8AdytzUX1fM=,tag:fSZOYknsLTPUYNYBYlCfnA==,type:str]
type: ENC[AES256_GCM,data:uLFiq46P,iv:4loHrhO+kgtdsABTkCvWZVpBS+E8JTAUc+PFeD8AWX0=,tag:2bO3wFR7d+B2YhCiRUT2iw==,type:str]
stringData:
    REGISTRATION_TOKEN: ENC[AES256_GCM,data:ixhQ2cT5cd1kdCSMz0M3dGKEusaRFHUy2AoHSJ9DwSgSChL76eW2gWRiAwV/uNMyCN9aGZqLD1duS5j5N6Hwlw==,iv:0p/JyVHqUPEWk7aiWT2Rs3DDPOTnk1oYG89tAkpVPXI=,tag:wHKro9vjssWI70Lakjk6cw==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSE1xWEYvUGlDcTQ4NDJz
            YkdrcVFVN1JYUE9RYm9ZSUViWnp2MXJXcWtZCjhIZ3ZVblMrY1VPc3NQbzJVMmd3
            WmxtOHA1eTJuaVNMT3QwWDBKVUMxc1EKLS0tIEhJNUg3dVVLdmdhVDZ1bkJlUW94
            VTBGeGJsZ0lSUWFGTjZqQmJHWHZaOFEK1K8cwEK37ATd3xz380xoYyrMkRw/gH46
            ZUOGBXE5Z5wnd3HAmW5jm6E0vVT7pYzyWUOmG/XKQZUResbcAudE8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T17:50:02Z"
    mac: ENC[AES256_GCM,data:haNFkk/xwPiLq2kLfT1ZQzddhGGOK4+aOf8PPz/9ojO8xYdZVAPUy2ZkBde8LSHVBAS91AJK/D9DIfkX7F9fqdAUvu920+z+s5VNPFg1orK/kuyNcp3S9J5CkiIU7bUVMRSFxE0bPSx2clyzYluI52idk9JTKYTU02E//2GTiwI=,iv:twJVWZOSiL8nAAQ5wE+7KfGIz8qUHXMdS/zcvhTInug=,tag:wRD+durNU4oawp6D57KUjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
