apiVersion: ENC[AES256_GCM,data:Ig8=,iv:v2zFuLfeCTmc6XVEBwdyj0CMm8LdA/gZFZqCVdhmssI=,tag:HZkx7U2m3cZ0CNJhDfYJXQ==,type:str]
kind: ENC[AES256_GCM,data:sSVEjqmZ,iv:61Q/TqlX3GtSXtnVvhJXm4nki3AyktoNuTfMpr4scg8=,tag:iBwfBKgE660auSuY0PjgIQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:srEaZM0yukzfZoCsnTJHghM=,iv:NbonCeHoY07LPo9a9ibG20CXfEKy5AaqOpkLgPDQR7w=,tag:YZ5HmUiELxth7ErD6j5knQ==,type:str]
    namespace: ENC[AES256_GCM,data:JkpfA5a79LCK,iv:OkHcWMXpet4O3GwkBpKoCtEbfbJ4r3jOlq+pONJUma8=,tag:soK0X2XQ2nFKgTVSiWkhhg==,type:str]
type: ENC[AES256_GCM,data:Uuj/LU04,iv:qGMaW/evyqBAEHobjk6NVjlFHYPFtzyLPiMJUg8SwVM=,tag:/EHratqtC/vCHHMHOCh5EA==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:OlkXC4mnEnonu6uVVnOLgVHn9MIQ/Hisia6C69UBIA7nxx18l0jgggxpOTlSxIjawgAn3ujTuFwX/nC66OegXJfu2wjMi8pvGsIbn+VkOKc=,iv:r7HTB/mDWs/WdQ8s+59cLZXNueksT721ZB41V/LL+Ig=,tag:KbACJb0K8hAFZTatDOD7Xg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:3GH/pfD/0ODkCrJonD/3w/DToiCOvlGfrs2bAjaqbzOsYhxr7c9udIsVsow=,iv:i4aVOGM6IwUnqDydsWu6EVaAOtW1asLvv48vzTjErbk=,tag:pfVw15bxdzquVWXnqRS8XQ==,type:str]
    password: ENC[AES256_GCM,data:LuiwCR+Y11xGsaAUHN4+BXCvGznV1bFhK0sRzivEBu/bl69cMiSWANSOYgo=,iv:L3DmwnzfWLEY2+42ufxNF1tSnQM4yF49RgXnGHEXKCE=,tag:KCv/Zl6gdSfqTpxnVcMnMg==,type:str]
    postgres-password: ENC[AES256_GCM,data:dN332hfU0ZJN2p+DkBiviV94v2WCeQoQirGoueGzAyp1qwpc8no+gOYiPB0=,iv:I5FYvBYketgpLdEn8oOTUJc5ZmZS8xxoea4rvU+OJX4=,tag:NsyZ6wVeGXMpl3vR0mkItw==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwSGFlak9uYlpiMi9TUG1K
            VnlUMTFtNmlod1g2ZEdYejl3RHVtMGx0bDBBCmtEdGM4UjN4RHBJdTc5cVpPVDN4
            c3c5OTB4aUxsclNSbTZHamdqUkEwVWsKLS0tIGhEbEkyNTlERFBKRGlubnFhenN0
            dDdOREtrMUMvMjViS0hnd2RqK0c4aWMKIQc3ry0FQEjDPxPOc2N0MgRC3lSbzEiJ
            IIlUctNTCu3K9ChjVZi/us5HZZE3phCOSVy2eNap0PfwJIY5qN/R4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-07T21:06:55Z"
    mac: ENC[AES256_GCM,data:feV5orY30M5vkgJ9kFLeBkE5dN9fmZu8wYF+kjpmMhKgVdOwUW/egtd+JZJhn5bXterQu7tyfbTLI1eu6ZyRRe4/2FbF05YGgyI3gdp3Bw0pFio6woJzv2hsJSkr/kwE7vagowUo6dg/kawNaXXuGjc/38dqyswyavkwcb9w04o=,iv:FNBhOZe1kTZ5qDOOSFyVeE4gXI2hA/Fqgl+8RnAClag=,tag:IaTR5z4gcyXTmabkcQQvjw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
