apiVersion: ENC[AES256_GCM,data:jl8=,iv:6E2TQ2KaxYJQZG6NwRVs5UExsaVEkiKu5ujbwINrnyI=,tag:E3cpc7O7KHna5UC4NOZQqg==,type:str]
kind: ENC[AES256_GCM,data:HTKfpBeg,iv:hI9SWy6K8tLerhMzpWnjoYAAwlzNHzHD5kpDXdBzDgA=,tag:3zIoXtfxxi1qAce0s/hIzA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:ym5rPmTGLRLxkZx6rEW5HVo=,iv:YwQVbbaR98JeeVz1HdPhJG3okuN0NrEVJq35BWYEh58=,tag:s4lpTfwbgcCpgmpMzPnYJA==,type:str]
    namespace: ENC[AES256_GCM,data:EyylvmWLugvf,iv:1eYF7kylErLT+G2soPnQ8GbGGp0SQSy3Uxp87FfxyRs=,tag:Dcoe9HxP5fAn6HcTGSC6yA==,type:str]
type: ENC[AES256_GCM,data:fEBW14Ze,iv:yIgG6E1GgkwM5g4GlGyvaY/VNnLZe8CcCgqojCeGV+Y=,tag:Lo7embeUBRqYpG606IMRvw==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:hDFWSMcrS3afvpfKDW1ysimV5rsjyFvfGjZPYwY1OLuL3jKwE4KEtk8dWzrCiKGcjwm6+E0fdYhWXBfyN1bInbzKoEe/BmIGbEU5fmNdwks=,iv:+6Dx6gko1W3jULIph9OHgHKEeDNOE6+igNf5/U67Mgo=,tag:fvqbLyQA4BZpHHdzl8PbuQ==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:SqHOVkkY8LrFRuALPcvcaDIuydQ=,iv:e5YdcMdznwFkyiAGgs5mr5dMXsTV80Ge/6hc5kIYrW0=,tag:19eoNQ9fbHnupj7uvtmEnw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:GSzEqNxmkkQt,iv:iqOxGvLQiM7l4GfpC7MdxtW2Jb4lDzE+Fwoq86WE+YU=,tag:Ug8+/01TeQzKlOaG2mv96w==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:z4AuWwloyZGT,iv:ltKWXvRCpneRnyM3Jx8Z53wzoMVa3ImPxEQ6PaMu3oo=,tag:HqtcjLxiI3v5sknvg38BMw==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:BR7zDw==,iv:6/H3xeF2yarSFVmh4SKoKbxt6awaCyuXkv+q9NwxRAs=,tag:A6tLa9LlxQ13wGzPpH91Kg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:IDHpHmYKU0e1PeJuVRKCKxUQ0v11YN7pDjH3SnWQeLt0YR9wiz5VwwCcitI=,iv:9L05Rdn7l3x6jQME4QgtBipMG97142gGJVUGNMHvGjk=,tag:998oYkv5Y162faslFlnRpQ==,type:str]
    password: ENC[AES256_GCM,data:nKE3PeaniwMtccYgL2WrF//CFPlcDB2NaBhQsGc+PSur3aocA0UqjnsNOns=,iv:hTbYsBqw1ZmoxYdevMvmZKkOfzLR3lpEVRr6pmgt7hk=,tag:X1wzgJxcaKqwOs6e42f9ag==,type:str]
    postgres-password: ENC[AES256_GCM,data:5Hl2Y51NydhDFmZloFKZg4K5VUC9XmiKs87Rq0ofHsnSogunXomv1aWAg2U=,iv:X7628LjaklwC4Urv+5iE/6sS8/GIJlvF1td9Gzfp9Ts=,tag:4rVY3bNDmpgXVXWmSRwOpg==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:9h1dD8+EE1ozuD6Zai3uiObS5zJ0sgvzEIFqmUhr6j3Y2vviwLlYudRkX6WcPBpS,iv:twVGGHIPrjsYTk8ff02lSmnH9GbvOUsl/visGIZhRdM=,tag:3NuIjqHNGwajpMSEdiVOnA==,type:str]
    AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:5WYeIxYaz8tbB0zyIjTBLmktxuqE0N9y,iv:4UfRHxyGhHaSJZuFhNFiJqzD0e/dxGc53Oh84GB5n4c=,tag:SBwoGLTdyt4C1QwiYMgDOw==,type:str]
    AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:pWwodO4gsBrKFtpk4XS86VVQJgnL,iv:jZi0sq94x2cwhz7rd0bmckSEdKkgCcI6sN16Z31EOiQ=,tag:8KEIEBuU78Xh9ek+TmbIOg==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTW1WVWk5YURCWDlHUzU4
            VU42QkZkdWx4VHFRTW9Ic0F4YjA2Q0kwelhJCitHa2ZlK25ndlNkV2tvZWhkS1dO
            bTlvb2cxK1RuQTZkeGNoUzdQREFVdzgKLS0tIDhiYjIvcVVHZ0RHbjJJREZTVnVB
            MzEyTXFBRE5CcDVlME5mUFlLZmR3L0kKfTsUIa2oqU/Z/uAa+9EeqzdAByAqPcdm
            dqlcfg2ZxL6vUbGT/xE9bLW0rIENFplD3Rq2esCiv29uhR6E/npIjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T21:46:55Z"
    mac: ENC[AES256_GCM,data:KUXqaRAaGE+/Cm2Fg25S5EFieHHtxmf9NGj75sbeKSn4Z2GP1/cyLXg7YOCoSLeI4zrrrCTrpjiqqQjsXyzJRTJjiMmhMcGUKPKtfnsSucaWVkvioky+ifyRSJr2yZQwsfHPMAuUIFHmW/h+XV0ajm8SNelpxjsF/kDg2/d5GoU=,iv:PKsLRe1FsubpSlNkUij9hIKcAJz9scKp4Z9MPFP/PHs=,tag:5HEsF/kM1lhDHn//VHAMDA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
