apiVersion: ENC[AES256_GCM,data:h5s=,iv:lvreGbADGG2BEmMbezJHo0kxWm4BROr2h0OxDj9FTsI=,tag:FMLRr4C7kG7QjHWgS1XlVA==,type:str]
kind: ENC[AES256_GCM,data:W2wvaeB/,iv:5DmzvoW++KCEtvxHIqrKv6IlwCp6ml/jiPkC/uQNf3o=,tag:5q+fJWzbIPsA9nlMHUiYWQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:QJTsZ/b0WhlOKG675ASxbRI=,iv:vDZPm8nAwr+EmeT+HAgm6vn3SDeXzG3ThDY2YIgeJoc=,tag:ypw+XSyodt1cBtfIXS9fVw==,type:str]
    namespace: ENC[AES256_GCM,data:zDmJkWpmLepA,iv:vPWOcyU2bth9mBQe8Xm7d5aOVvf77XWIwUIOrPj5o6U=,tag:mCswSB0WOxgOWzOHE7lBIA==,type:str]
type: ENC[AES256_GCM,data:tCzKk7R0,iv:4E9s9tRnhKrFLVUFqkGsuFtX8b8j1vUm3oQNB8gqllM=,tag:WbyKJRadP+6dHkL33iZOkQ==,type:str]
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:1uIxKlIL8zM/1zdLQcNDi42ZJcgWJ+yH61Wcq2+9nOpi5qGxrx+9qYm+b+xk4tMJx6r5D28k8HCVgvrJkqPxQf4ZN8LaaE6y2OONqexF+2c=,iv:Gujzse59er566Vv14Q8KldVri5Co2Z3zliCOr+DtyfA=,tag:tM8BC+frFw/QjsA6VtAPnw==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:Ph5jCWok6sSxpTNoLJeP0uoXGDY=,iv:1Yv7fKS5sRJ4ICPO1Z+/sCKBqpsvkB2SbA31WtdgSJE=,tag:rgtFws2XRCcdqMWrW/+Gvw==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:+R4VJ7ZeugLd,iv:ZAAKfIeoHJnSvUVxjfBoxQz/Pgl8FK7tM/EpPT+eVvg=,tag:Ja03c7IFembido2PG5xRuA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:SS7QsUD5J5V1,iv:Srh7Pfrpea41gH+mYK6+E8MOutjijeNIC/RgoofPwpY=,tag:tHmYtIkntsMoRSINvKJNhg==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:hNt5vQ==,iv:CZvDxTNvCyPyYhAJjOrc4YUiqJzB8cAUmSwnUTe+/+M=,tag:S/4vBzmfvBgnc++SjXdBvg==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:FvTgxgkAlSmv1HHN5r5fQIQgqvlhg3zsCQ9mQz9AM0Kt+VXiM9p7LqFq/lc=,iv:6wetOKomvBHVRLuLB3KIZekPk4fnMZ5gZWUq18pruCE=,tag:GfbRJZ/ffOSh2jB3xb+cfQ==,type:str]
    password: ENC[AES256_GCM,data:ro/wkTSMNmRr5RzTDon9eBdtExKTvHJ8RBbPjHJgXQ6eh1tMJ7G5XgTOqAg=,iv:pb2iovoohvGBNHBIjq96DnEooDJAJcmpQUtn0az3dG8=,tag:yJHaqLtR9z7d0fL7Q110WA==,type:str]
    postgres-password: ENC[AES256_GCM,data:XUZIHeg9ARWL/zEarB+NhUX650RC4qsgdFbUZpT38Unn3rEGfayMTouSUpY=,iv:MHuo29Bti+K4+Nr09uDcDg6FWW7nYQFpcbpSjFjx3ZU=,tag:ceC1GsJGRwrfqAHueUHPAw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:1XhS2RPjMz4dT+gixnLCMnV+UTw9D0rIzt8ELPL/Ru4TZizXcrfsSC82hRN64UwV,iv:dNdZ/tlqzu7esMxwdSZNZ8z+03LXAiRX8mwh5eZ4YlY=,tag:+YjGC7gHSS6XpGVWJI9dtA==,type:str]
AUTHENTIK_BOOTSTRAP_PASSWORD: ENC[AES256_GCM,data:Xv8Xq4keT2UEpbBwfre0+rzWODnRsM71,iv:cJQtBJDO9mmBTlicU6c6LKxV2ptM9Vo140aV9rLBDdY=,tag:GEolQ/LlirIwzZ3Vk3vqIw==,type:str]
AUTHENTIK_BOOTSTRAP_EMAIL: ENC[AES256_GCM,data:izD3xcdloV9YQHz4Y5FE5C8yQ5hU,iv:sThNoZLWwf06NYHTWgsMwvBQSb+eJ94lsrvkv+PShiY=,tag:gykNvGOJaxXnkfMfAdzuMw==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoUHorQUdTek1lU3VkQ3cz
            MFYrY2pGVWFhNnQzNy9wUlBaNE83TlNVUWpVCmhmQUZGeC9YQUhxS2ROWDBlMDJH
            VGVxSGhkbUw4WG0weEQ4UzZkb0dabEEKLS0tIHBUbDNuNUk2VjY5TW1jTFVDejgx
            QmNTYzNlUHBHWjNFbWlrSU9GeDR3K1kKoBn3ktZI1WTwKRQ8e4Rqv98qyq5d02yT
            sk8nIhLYSoJrREvU6wosBol1GOCcVe8FlKW/Uip/jLI8i9M8cMlbCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T18:08:58Z"
    mac: ENC[AES256_GCM,data:GEogXO0syP1Kb3oZTkorjJF96bS9a2NDXGAAfFmAG01Z/Jt7yMrx6wwOXsMqDiikiP8BWYlfQ75hCwgdXtG/I1b2XXxTXwyTnSIpgWnFQL8CdCgg257ijTqYWjqQ5kdKlzkbK/iIjxrOF9wEYn6XqU3QM8phrbmY4fm3fUtfPuw=,iv:lW6cVYt7mVMApSoGTfmYizRpC9GIowMqgPAWUO+HGgg=,tag:toR/0D4SfUau0Z3zTUXLSA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
