apiVersion: ENC[AES256_GCM,data:brI=,iv:VIJ2eYGRihtJ9SXUqScAVj8Rl0xgN3zFZBVzQ0iRZL8=,tag:7s1ZIYcq9q5UHxTGkKfJ6g==,type:str]
kind: ENC[AES256_GCM,data:Ng1kfc2p,iv:VjsBPDCUlBN61LVGHh1fDqkvcn3qFqFTJ1aH4ahppCI=,tag:L2ikOm2hWJfSeJRy49Iv1w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1+9iu7jHiYSf5fEzbx7+un4=,iv:hLvuyjaJyZXrj5yNBOVR+50w6Zio1hDmJF1x/L8eMro=,tag:qytWtFq/uTdgnmvdA8Lc4A==,type:str]
    namespace: ENC[AES256_GCM,data:1cRgt5YDLLzD,iv:iu6NU6MET3emzNuktWLlkC1sRef4sIA5NKLNiZhHOjA=,tag:UDGrrg8+ZC+IPFGNbg/5vQ==,type:str]
type: ENC[AES256_GCM,data:PTbhZgsZ,iv:IeMWZI+vY+GT1c6VjvqJiam3ujtOHp6BL0rJjwyndHM=,tag:r9jr6zQGE38YkysJjiQCxQ==,type:str]
stringData:
    NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:VEEnl6c=,iv:C71HHLlVJgmA/PL5zAbGOfj9/txbrEbq6fhacLcFkm4=,tag:lvuVppNastc7zvwI0KDdHA==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:E7cdMBzlp92srCogaVSKEGDDKtlXwaBzdhsJAddSths=,iv:h0PJh2M7DS7Ix27ElDMC4X6ZzfKSyh49N5LXusMmWNw=,tag:xxO1zqp3mzsS4NkuyL7jyQ==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:98QTzRG+3emI,iv:yYUj8lrvv67FD6bbfZnNXHNim8vaS/p/xnYFaVMHQ8k=,tag:nYAH5B0vR4aGAHPeozF11Q==,type:str]
    postgres-password: ENC[AES256_GCM,data:RhZzRmc9cUkEBbSPwBhlfJTf9U9PA66J6ENHghNu7J8=,iv:igQk8pkaXRIzyJomgFvUT5c1BIxPzGtdHnzxBUeNWDU=,tag:KdGhKhaiuGH/nXFVVqFl0w==,type:str]
    password: ENC[AES256_GCM,data:DFtHgf0DC6x3+76MruKhdTyiFfE5WC+8q3kzk+HUDM4=,iv:8a+MLx4f/RjXRkoxh45Nmifw8I0RWhZm3FBjLxJQVnA=,tag:Iram02nqL/JM4ycNPOmeXg==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:wD/9IbSZmWm76YPxyppTjXsFAUv1Bsg6ntPuajGwXHs=,iv:E66sLKyLiko8CzGvFySHf+KB6ajDTbZXzYIswqI8Ars=,tag:bSuc39DnuuHC2ZvaLWsmfQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:DAIrBHQgU5Ex,iv:OziiUat8tRoUmx0PArjjrwM5QruMmxjLYQ8ioF59leY=,tag:WwijHAXkj7BuJjlE15bNdw==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:I28VQIoEoUaNlUknGITEuUTUS5aJw0T0IKaOjWBSDlmTan0+akSPXcY5fwo=,iv:Z3bzWSBW7eK1+8wNonfRckBLJr0hdNEPNzQIqEvS8So=,tag:Uay0Ts8Y25Jd7tSL0dGNAw==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVTkFkU2pOdVFvbENrOEpC
            WUQwNVdqNUpJWTYrbVBkZ2RUR2haRDdmS1dvCnFxTW5qeVc2Yk5ZaW1jMjRWak93
            cnVZVVliL21GZ2UyS0tuMVpxNmtnSFkKLS0tIFpxY1Bkd242WDBPNUlJSXRoRFI1
            ZDFJblBSNDJWSUZFeUFoaFZiQ3BqU1UK6EYh7XOVv0zLf1bWTI08A7TRiEtKws9u
            8m62KilEg7R5MQxXeVfYjG5HmtGqLPE33S24ubcroqgaGv8ydolGxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T09:55:03Z"
    mac: ENC[AES256_GCM,data:mzSIX69MWHbFG8xl2dWdS/0T8PpqYOztRKUYefcbxrYDClX3fayGFvhON4qvGcm9QgJ9WNULOKPb2dDyFTbuq0J3hY4EsNWNC33CuZgGCltNlTmkmiM1RtUcWtgUS+u3njk3o+R8VR4AG+wqRN5eysInFRzLBkBqaVGUY6RkB9c=,iv:RNcy1Uc2jviqZkf7tyGUDf4Cr035gWsdTqBwvZExrEo=,tag:0MXaUIsTc2uAThYXcKn9gA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
