apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: authentik-blueprints-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./vaultwarden-sso.sops.yaml
  - ./nextcloud-sso.sops.yaml
  - ./immich-sso.sops.yaml
