apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: 2026.5.6
      helm:
        valuesObject:
          authentik:
            existingSecret:
              secretName: authentik-secrets
          postgresql:
            enabled: true
            auth:
              existingSecret: authentik-secrets
          server:
            ingress:
              enabled: true
              ingressClassName: traefik
              hosts:
                - myown-authentik.local
          blueprints:
            secrets:
              - authentik-blueprint-vaultwarden-sso
              - authentik-blueprint-nextcloud-sso
              - authentik-blueprint-immich-sso
              - authentik-blueprint-tuwunel-sso
              - authentik-blueprint-jellyfin-sso
              - authentik-blueprint-account-recovery
              - authentik-blueprint-mailu-sso
              - authentik-blueprint-login-mfa-optional
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: v0.1.12
      path: gitops/secrets/authentik
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: v0.1.12
      path: gitops/secrets/authentik-blueprints
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: v0.1.12
      path: gitops/manifests/authentik-backup
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: v0.1.12
      path: gitops/manifests/authentik-public
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
