apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gandi-dyndns
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: v0.1.8
      path: gitops/manifests/gandi-dyndns
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: v0.1.8
      path: gitops/secrets/gandi-dyndns
  destination:
    server: https://kubernetes.default.svc
    namespace: gandi-dyndns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
