apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phase5-mail
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: master
      path: gitops/manifests/phase5-mail
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: master
      path: gitops/secrets/phase5-mail
  destination:
    server: https://kubernetes.default.svc
    namespace: phase5-mail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
