apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tuwunel
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: v0.1.8
      path: gitops/manifests/tuwunel
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: v0.1.8
      path: gitops/secrets/tuwunel
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: v0.1.8
      path: gitops/manifests/tuwunel-backup
    - repoURL: https://github.com/Pavliin/MyOwn.git
      targetRevision: v0.1.8
      path: gitops/manifests/tuwunel-public
  destination:
    server: https://kubernetes.default.svc
    namespace: tuwunel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
