apiVersion: ENC[AES256_GCM,data:xvQ=,iv:/46Q13brKKB/OeDr4vD2x0eiNolisX5Aoq+SsFQzmIU=,tag:e09I35Falr2Olw9IqliY/Q==,type:str]
kind: ENC[AES256_GCM,data:50V/BAYu,iv:BHEC2WucgW0ONCxGrDeUZrBV/32qehCXol1TvlG/ieQ=,tag:VgyaPJzPLMbyYsLx7vnBhA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:HdzdDf4gW/AnZyRu7Dp61H5CVg==,iv:dW0VZwI5VM3/PGTvHlybrLE9ZlPMj7SxHoq5/v0VmBk=,tag:5BcEUpBO2r9ErsWxva3tZw==,type:str]
    namespace: ENC[AES256_GCM,data:TPcvLjhn,iv:d5NLsC5fnTb3tAJu0L9g6VumzgX/GQ8s3KF6ysdD/3g=,tag:Yr/ndrYJyRIiMH8GJNGVqw==,type:str]
type: ENC[AES256_GCM,data:c6GJpZ6N,iv:a9RzdvZitEQTafZNHcKqqgmRf01C8lXe+TWUpuEdZjo=,tag:+WyI1htJEtjRHxK0IoBEmg==,type:str]
stringData:
    immich-config.yaml: ENC[AES256_GCM,data:DcUpHygl09uv6V4GQKW6ZFZujR8sTXbZWBiTYDxWacjiKp1TyAYituOZKM/a1gax0YRD6+8oE3nC9u898GP+4xTNUzFcu5oG7qGyfNycC97bl74cOCkv/b56UpJHEKafVgZCOJXLHcjC83mUK6pLUsxly3KNrGMRhYUmj0muzBsNDIVP8NLDo1m8Lh1c3DoV8TLdWHZpe5fiwjmQb27NSGTcykWHB7glh1pAZQ/zi4e/Ez7WJSPpr0oStz0vVoz+QDGDBFMMTpR567ht4OI819XUZechLrrf8iub7/Is/IK5PwRAARtq0rqk5i3ffy5kpI5XCHw=,iv:QXX60IuhlXfvVSgv3h02dgXMu1yObs9BD5p7AiToRQg=,tag:GJ/gaLkDFZZxBvZxKko6Lw==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3eG9SeENSWURRR0ZlaXpG
            ZmJMdThRUDRiNExxcjVUbmJrSmpoNmRRUEFzCkY1MFRCdVBmeEZ4QkNmbHlJdkFa
            dXEzWGRVTmFodnJtWDY4STVUWHdRc3MKLS0tIHRKVVFBQVpsVlBQUGJMYXVjMVRs
            dTlldDkrdStCdnNIOEhIRm4vdmtrVHMKCYAEs9tdKV6xMX19iyBrYOnBTcL7ch0z
            TXfsURPJdupqT9F2V3bm2gw1ixXrPIxqKbH26V4AxKnbXN2gk4urpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-09T13:46:22Z"
    mac: ENC[AES256_GCM,data:Vram6b4uCnTmOE34pQ9LzbUYcPpiY3oo262kej8H9Y+L4C3NHgC9WH7HqQZy23PtB2GoUdd/MOU4quW/MKLDvQ7gqVUCm7J4qTJR7qOXUilzIzFMQ/hnIMbl3J8CTwnvGP9XgTvn4CXSzSnSRXyQ/P7b7hLs6UQSayuEyvmdeGc=,iv:XbjW1vA6Jnf3jIcY4CFq7L8dXm4kU3+QAnLhOTKHStc=,tag:ouIzWyWFPEfNbRytf6pPoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
