apiVersion: ENC[AES256_GCM,data:Hug=,iv:qq9YxNUFj4wzved0HdXhSd0WHRWbq2FEmW1qbpSV78E=,tag:hY++O1Rb7Libb3hSechL2w==,type:str]
kind: ENC[AES256_GCM,data:Pmlw8quW,iv:e/8IQo9aHVF0EKoDXvr0nDjDX/PhHweb4TSlym6ZFqU=,tag:T44VLLqEP/w9Ir1FnZi5pw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:UNpDXEgqpOyyWepsxzA=,iv:VLNR+LlIHII/56XAEP9IwXnPEkKicLN/wIFjfYjOG0k=,tag:HBNwg7yDPyovrvURuMrCkA==,type:str]
    namespace: ENC[AES256_GCM,data:xkNroQZe,iv:KpxjpqNkOjRoiWC3L2vkAq2duWrXuK92WlL0HISFgj4=,tag:CvV2BSoL3ufc0OsEBp9reQ==,type:str]
type: ENC[AES256_GCM,data:8/g/b5Hw,iv:l2AnqCRjiEgRKPexWKzRcFAmn9w+XvAfrTcFK51bBx4=,tag:raipz/pExq63T6PplKUEqg==,type:str]
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:NWVAj+9t,iv:reMJFgkxeDscFEOLUwtr3HU7PrSAFtxQ57ZCoFu2It8=,tag:sMJEBvPH7jrn2LJl0smtDg==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:PPiidtBzD8Sa3Ss18WkGRFcYigmlxB+e7MjQZlYw3qssulogSbAp46C0vSQVJU8w,iv:hbSd0qDWHQauLOoPiVszRgEI3iUpRL0xEJiYfghjdrY=,tag:1PguEYfRXfwNrl511p1SuQ==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:Fm62EV9fSLnoDg0BgLFdoqdKC1lp3zm3jIBoUqY9fONx06QdPVqajJ+8mRks4e9i,iv:g6Md+AOkNqdfWz7GdZBh+0P2WNxQmnpgfozwpdBRnQE=,tag:o54ujHjKtLmmQItFaKiofg==,type:str]
    ADMIN_EMAIL: ENC[AES256_GCM,data:6fUOonVh4CTdW2j7qqklIU5R3UvY,iv:7c/LhG+zn+9fGWaiLDu8OdpXjxzOoBv7xzrbJbwk6a4=,tag:wEVGVzMOwZAcoKsroX4Agw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:ZSuzjIzNh/WtU48BFhZv4znFK7cdfOSL,iv:Lai1eIB8TDTp4IpZfOol8y3bFvIzSk2elWeoPIY4RYY=,tag:yUbvnh0tq/Vwuk0A2kzQUQ==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRWxpRjBxOFBDelRvb25N
            dUhvNi9HcEN3VHhRK1dtdG5KZTJmKzU2OG5RCk5jWHBTM20zT05xWGVGZFh5aDMw
            cS9CNTUrRlJFd2w1b09ESXA5bnlDVGsKLS0tIFpPQytyZWJsMHVicHB5eHJuaWFl
            SXhGVURhYURERVc1ZGxtNmdyWkR4TmMKkrrbJDV9kZBos+5+27PEr4R7gXvS50Mn
            yCBAuP3fhBK2UKJT0Q/Z21MCcOSTl/DDcnwAv471DvCok9kRl8gEEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T17:54:15Z"
    mac: ENC[AES256_GCM,data:+WojN6feMATl7HfPAGw+cDm50FkS5nDoGybSaQfs6JujSIxvH9LAwpL3a0Rm2CMS1Mltm9igiIJaJQVbjzeXmLlFlycNQ+OCOSZu7zcdAKcxOBvuwRY/agDJyvYydjO4uYohAQT//k0K/LWMme427vdrkg49BlpgMwoC1/3H2bg=,iv:2DkXhpKNiZeVTsS6/CtNyKerbt86NeltmtODD7To9t8=,tag:VE7wLQDywX4YP6SDN2OmSw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
