apiVersion: ENC[AES256_GCM,data:M3o=,iv:iZPH+B4FJujhfjtdhyVOr0JodrB/M/n6ENWn9K3uwi4=,tag:Rk6MTX+BLBpfOGQBfaGw1Q==,type:str]
kind: ENC[AES256_GCM,data:zPAoVbFA,iv:eQEaHfHa8LjfM70iFPWWttl0t8Ccsnn2gj3oi3Biq/Q=,tag:sAGk0OrdL0wVSirNCnw9+g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1kG61I+rDYvOcNtjcIR8JzUsEQ==,iv:20HLWxGWJbd5EwFLyh3w4TZEhxZP5m4WInjMWLOXKsA=,tag:S/B/ib4xKOXvWYdg4UMJTQ==,type:str]
    namespace: ENC[AES256_GCM,data:kbwFFy9p,iv:fZrg6fww9sdN4S3e+oMd2zHQnJmcnuJxHeoXOceRt3M=,tag:/+uAxC2lepfaZFT0+27+2g==,type:str]
type: ENC[AES256_GCM,data:SbemeakA,iv:7TOTs6qmWnl2Nul5ar6UpIXaGfipBvNWnTttkLVoQPc=,tag:8p/GgsJh4TWu/iV6DdNMCg==,type:str]
stringData:
    immich-config.yaml: ENC[AES256_GCM,data:XM2A9h6lOvvBps2m8UgyE1fwdot8xg9NU5TtUqYxlI5MMBnCOIisdpj2UFUeDPb0Jbh/iEvi+qsBog1X6amEXnd6OtlmBI9vN7hg2vSalv5C7GhdfLkhop7FkjWwpVqnyCHXspjv/K+G/GW03Y4dtelQ86G2kCwWJlyXypnnXcYpMu25m3W5p0V3rT5L+uEngI9272s63T72C6EabHKTK1VFAn+SsZlX5pkf7kLa5P48uDTwSKGVQGJ8ch8LkrSTLQB692zUPVuZkh26OlkTtyIMFNpT1thpFHi09rBXW3bFTbTRFY5FbwlKmVx01JDiqA4=,iv:mAXfqfn480D4jXLjMN5rQgMu1UVxVi4s/w2yHsTqOsg=,tag:Izi0PXltg9xBvNTg4aIKGQ==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWWJZR1dRZ3pMT0VYcFBB
            d1BoemVvb1lMNUtDalRvZ1Q0VmRUMXNETzM4CnFzMHVjZTFhZS9jUHZQSWVnVHVm
            NG1MNjRGci9vcnd3S0plMTFKQ3BZTWMKLS0tIHJxMkNkb1RxcW5ZRzYyU2FINDg1
            b3FuTXhENDVMQVFhMVNWaUZlSU5VWk0KSCdkohr+pti7qnNIyEgB/vkAOZPAiQMF
            ZMAiNkJSNzgeOciCjR5AyEDkn9qrWrn1OBkL1EWZ+0uJKDEL4h1c0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T15:36:12Z"
    mac: ENC[AES256_GCM,data:B73IAWzsyd2co4CowMV9I9yodWoPDmNLyg7/dNzhIQDDG+8K32BLmmmnww9aPw7RPzZ4ZgUd4JFkJUdG54U9KWxoKRvZ9s8haRzv9lglrWJe/TMH4EmbcFEugsQKGmD/ch0OJJB/DEuBiK/LZWcY1Hi7kPHO+SFw4yRWoN5gaic=,iv:brw9GDQXWwtjbDZevFHeGnwT8sFO7T6TqhL1pyPeb7k=,tag:JHLdlt3TYmcm/aXa5PqTBQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
