apiVersion: ENC[AES256_GCM,data:kKA=,iv:dRjNUcj5S1PAuzj65o2v2KNBZsoYq0d2u8Nr0vJ5djs=,tag:0/PBYGTNCEQPKXyJGI6CrQ==,type:str]
kind: ENC[AES256_GCM,data:h0yF5TsJ,iv:LTASkWAjxQUL7+hWr/1GhLd7CHyFzsHB8wfoIv/9+ts=,tag:t+7HJhox1brOKixzc2eQDQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:uHYPL/A4zrvWZxzvus5I3vUZ,iv:26n3SWyad19ywBiHcuAhtCEokZ9CE9YlftIzb9FCUcI=,tag:jcy1TJvCXeDb+AzegQDB7A==,type:str]
    namespace: ENC[AES256_GCM,data:7gC0QL+diEJWyQ==,iv:ncnrDeNwt9RM7VrJl307zKnvbKNh3HfD3SkOv9+NG6E=,tag:Y/yOeO9yNAnWpPYDirC2eg==,type:str]
type: ENC[AES256_GCM,data:IWrrnF54,iv:rJYz1Vc64LU7rtzEjK4SEmrP94yK4LEdTkyVH96jcdc=,tag:VPEuBHG9bA4BbqdVirehBg==,type:str]
stringData:
    admin-user: ENC[AES256_GCM,data:uhnIE/E=,iv:tRcuILOgSq0rI0CBE7amUIYC9PQAWY81a2tDxM1CVIg=,tag:1o14ciKRPP+oj8hqG6kj1w==,type:str]
    admin-password: ENC[AES256_GCM,data:G33G/E728z4qkRx8LSj+lw7qtKq4VZrr,iv:6p7A1yWWzSWaRTzAco+Gc1T//0pYSv8dyxshzKkXdt0=,tag:6pfUMAgC+wVX1rn2axbu9w==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBycnBsa09ObXdEd1pTbDZP
            eTkrZTdMdTNWQ2hLVGNXNmJkRU9ETlNHL3c0CnYvZVZieXErZGluT0krV1QyeFZt
            ejhKMTZoODU1c1FhcVQwQlU0a0ZyYlkKLS0tIE5yQjl1cGFVOGd3RHVhMngxM3JI
            NmpGZzdkekd0bktJYkcyUWpEek5pa0UKDz11OfWs1eHrqRnK+XPVGh/7qcK/Dhz3
            raFbEosxd0pf4DJ5IFsygIoswykEyPkDfyYlsuU5R5PHJNh3km+2Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-20T18:41:19Z"
    mac: ENC[AES256_GCM,data:lCPyfZLRTz4ExhdqU5wN2NjFpiNAZvE6NSKY2OMHaYyhaKpcMK3qr7sdk9GQhnmQLAUNGvk1hv+H0C4fqxdZm9IMLqCJDAcqXbh1QnkTkNQZlWIuySR+DZ3g44vr09GZN65MkAMBnAZMfQADKwSw5CD1/ojUpMaroSlTcwdw7rI=,iv:H0PKG/gvEA6XMRrkUE+jPD12eGrKjWf4nU0mH+6Cuyo=,tag:PylUpCRMW6z+m6jtiGB6JQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
