apiVersion: ENC[AES256_GCM,data:Z0A=,iv:hS/COW7SpXL/pQF4saXTgzpGvwaJAc5DI0KAXmondeI=,tag:lDnIBvkxHwkAFquIsogOrQ==,type:str]
kind: ENC[AES256_GCM,data:x39NaDX5,iv:U2fazVP4VwMxVGT2OYAnpJUIvVGMY9PerkMNWG8HeJw=,tag:3OdxRqhxgVj4eLq0NLjQIw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:OQHqkeTDQKUWKJFa7XQhu7lKzw==,iv:k6mp7lvqzlyTG1fb/WtlAZ7Cmfcw+yDimYe13w3uG7o=,tag:nvl/NFg6vvqZhkJyxym5SQ==,type:str]
    namespace: ENC[AES256_GCM,data:Fdaw8Gj+kFArHeo=,iv:aOfWvmJVIax++MBZEEXffhk6v4es1kZplLhKQBDuguQ=,tag:9HV3LIy/2XcL/Z3EbGwsIg==,type:str]
type: ENC[AES256_GCM,data:3Uxoayia,iv:3WzZX+/0owb0WXyLsZk10ddV3TEz0rNYUn8COW7u+Po=,tag:axza7VV4pC7KzQ5U2yh2tQ==,type:str]
stringData:
    TUWUNEL_ALERTBOT_TOKEN: ENC[AES256_GCM,data:B6Df0TYSBSAlGyyRQwvkygmEx759IaZDDI0m2buOLdk=,iv:aws7BIldS49HVzHWw60fN9+iK4yp38hOfhgjRViuR7o=,tag:2z+8q3AcFvWYPwrtwmFf4A==,type:str]
    USERS_JSON: ENC[AES256_GCM,data:n5oGSYUusVVPMt5nklvplhRwE5GHuTphKuvLQy44py8gWXNN3Em9quDyP+9sbVdzyoRJOVj+ku5mr2bv/PqK2w8S5xNfYLwZ/9jAjtopASWcThLeVocHGh9ohoneARdBY60eosh6BzER/+EEr6dLD9JleUzxzKcJXopHv1twn10f6jCCESQPsDl/YpM2BdMvIo6UMCHuMd34SrN5OlqkAJgY5yUypZ9+WJRz7NZstKHwXq21TDWFzMuAcqhmVellDCMVtjwnyz/ufshacYUyyPf8ZaBb25s53Cc5cnrdGZ7DYezqkehHwniq82itlOcPPKSTyJJPls+W8Nu5PngkEfXsz0NwaBipc7Erqxp/7AcbeIKL87bu5BY6HAy2/qZF1gsqpOp401qYgjskuWmU1fLXTm6br4pREA==,iv:WS1hUGB9tgT7aRlK4sClfbshzicLl4WHBSA+Jh996oc=,tag:E7Qa3MxSgHDdXGD9VFrknw==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOHVWNkhCVzNVd3hxMUNu
            elBpcjJDQWlzYm9PaXllZ0NIV1JzdzlXZGpBCllWd3pHczFMbWVZL2h4dDlLeGVB
            VGhhcno1WkZwZzNkNXlnK0JjbHNJUTgKLS0tIGg0bGhXRXl6NWFWVWs4VEhaTGtC
            MGpJeHV1T0k1OHo3enBqUFY2aFZMeVUKVWmLuNMchnpo5dwWF+sPML+zDxfGarRZ
            HNZ9R43JT212RusuEYVj2vsPGQbxrWJ5IoFLRCzpsKTDdG4sCgM2BA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-03T14:18:32Z"
    mac: ENC[AES256_GCM,data:BUja9hCcpQhxY8KP47npcVnIl+YXZmJappRBJxALOG+c37jQUH96TYB7LHOZWt9h+P0x2+LrNdSXj7VYAJMhHyLZY0xaGYL8ZsWUwCX1Y2O15MoAHZGUR2HFjzFkaaegP3Sgi9kGnS7zeVKz70w5M2xCoM9pNZG9HMBnuMbjRYc=,iv:Q34pef/vcvy7mRZgHMPm35SvUU6Ctl8ne51pGY2hzNA=,tag:f1jmgAEnVS/mx1nyp+7n5Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
