apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: phase5-mail-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./phase5-mail.sops.yaml
