apiVersion: ENC[AES256_GCM,data:0fg=,iv:wOLXaB07a54On3HnXIK7ZDTXngR3uS1HuN7RNi3QmNI=,tag:cr0fcujmTBCU+jQy+Op1ag==,type:str]
kind: ENC[AES256_GCM,data:fSVNij2m,iv:Iaej7p1fH53/v5BSyvXSIupa5y+2iRrxji73glbhTRA=,tag:pp6i8CZ3tsh3NZsAx/6e3Q==,type:str]
metadata:
    name: ENC[AES256_GCM,data:LXuhQWe68etdiiDUmgre5ZN5R/Y=,iv:cRFJzQDsbeRRQKXe5lIrgOQ9b4ydim8FENWxROJ7hCs=,tag:NhGYuxpnIUzjgyzirdzg+Q==,type:str]
    namespace: ENC[AES256_GCM,data:ClN93egOHM00D+7X,iv:HPNrMXY2BfsBrDoOWmx0sc5DI9fkzXaIUDipeb9cUF0=,tag:u5w6sxPFkVt3HLuMVqVzOg==,type:str]
type: ENC[AES256_GCM,data:w1mR3Q8o,iv:8STpoVpu2iPrHVdRrpKGG3r+Ck24TCZLfPYC0yuaOWY=,tag:fbE7gb8Sj/LLobicMnbxUg==,type:str]
stringData:
    GANDIV5_PERSONAL_ACCESS_TOKEN: ENC[AES256_GCM,data:dyL25B9tq6A2DmZs5kSOhDiFHm3yZV/y3qKo+jaX8qKcXmLozGXdew==,iv:tfjiU4FNc/NLR3QFVtoN3wX6F0mDPHOnyFZfvt2dhBw=,tag:M+BZnq+LphhZbhdIKW5gFg==,type:str]
sops:
    age:
        - recipient: age1l6tfhv38sf0rdg4kw7l6mjugp7jvsvwrf3zul3ptz43cad2pkucsg5ks42
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YklGUnFWWXRsRW1IbFkv
            SFNUVXY4cU5BaWtpellkOUpqajVqcUJzeTJBCm1RbDVSeEp1Ry8rdHJFZjUrODdN
            MEVtK0lvWnFidk5MVzZOeHlIakcxMEUKLS0tIDRoK1o4WWlGckh1S3RnWmlrT1RE
            c09FbWpjQ2o1SHRNTFBGdVZKd2hXYVkKj2FG6m5bnC3tTvnxHXf51D/g2W8rvJiI
            QbkNfIn4QAS4rH3JuBcZ/dqVUPNSSnvGMtf7whnUJoq1TdmcE5rbzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-21T23:57:37Z"
    mac: ENC[AES256_GCM,data:OtIx+HYO7iJISjUpKNrNVPu9YgwtAM4KFZfBMgU+w8F6lkHbloTuFPnCwJvt6VQ2llbFeLDMquxd9r8s5FiQQYTqi/2Z6eN73UH0/05qTT1zR4BTieYi1/MplwBWro7yoTPPazLVsT531U1AuuNtZdrAjnhg0Ia3XIyNBzDsMTc=,iv:Jx7ty5t10ERHblwjwoHpwDFgBuU44hFPPURTt4mmHWE=,tag:cKEONXK3NrO5HGyFuNwcUw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
